### ISSUE TITLE
what is zzz.R supposed to do ?

### ISSUE THREAD

**Issue by sneumann** [sneumann/mtbls2#11]
* R

Why do you have the zzz.R file; what it the code supposed to do? It
seems to me it is a script that you use to format your data, which
should probably live in ./inst/scripts.

**Comment by sneumann** [comment]
@lgatto the xcmsSet needs the paths to the *.mzData files
as installed on the target system, if e.g. fillPeaks() or plotEIC()
has to access them. So zzz.R upon mtbls2 package 
loading will replace the dummy file paths with the correct ones,
this code was taken from the faahKO package and adapted.

**Comment by lgatto** [comment]
Ok, thanks.
